name: DescentPlugin
main: descent.Main
version: 0.1.2
api-version: 1.16
permissions:
 command:
  default: op
commands:
 start:
  permission: command
 stats:
 setgame:
  permission: command
 setteam:
  permission: command
 setchamp:
  permission: command
 getitem:
  permission: command
 stopgame:
  permission: command
 patchnotes:

 
  
   