name: DescentPlugin
main: descent.Main
version: 0.0.1
api-version: 1.16
commands:
   stats:
      description: displays current champion statistics
      usage: /<command>
   setteam:
      description: sets your team
      usage: /<command>